package main

import (
	"encoding/json"
	"fmt"
	"os"
)

// Config describes the tray this BMC manages. Generated by Ansible from the
// same variables that configure the tray's fake GPUs, so identities match.
type Config struct {
	// Role: "tray" (GPU compute tray, default) or "nvswitch" (NVLink switch tray).
	Role        string `json:"role"`
	Listen      string `json:"listen"`
	Tray        string `json:"tray"`
	TrayIndex   int    `json:"tray_index"`   // 0-based position in the NVLink domain (CBC chassis)
	ProductName string `json:"product_name"` // the tray's model, e.g. "GB200 NVL"
	// GPU VBIOS version, as the tray's NVML reports it (firmware inventory).
	VBIOSVersion string `json:"vbios_version"`
	// GPU profile shared with the tray's fakegpu.conf: power (sensors) and
	// NVLink bandwidth per link and direction (port speeds).
	PowerLimitW   float64 `json:"power_limit_w"`
	IdlePowerW    float64 `json:"idle_power_w"`
	MaxPowerW     float64 `json:"max_power_w"`
	NVLinkLinkGbs float64 `json:"nvlink_link_gbs"`
	// Firmware versions in the inventory and the managers (empty: fakebmc's
	// own release); the switch tray's NVSwitch and CPLD firmware.
	BMCFirmware      string `json:"bmc_firmware"`
	HMCFirmware      string `json:"hmc_firmware"`
	NVSwitchFirmware string `json:"nvswitch_firmware"`
	CPLDFirmware     string `json:"cpld_firmware"`
	GPUCount         int    `json:"gpu_count"`
	GPUName          string `json:"gpu_name"`
	GPUMemMB         int    `json:"gpu_mem_mb"`
	NVLinks          int    `json:"nvlinks"`
	ClusterUUID      string `json:"cluster_uuid"`
	CliqueID         int    `json:"clique_id"`
	Username         string `json:"username"`
	Password         string `json:"password"`
	StateDir         string `json:"state_dir"`
	SidebandDir      string `json:"sideband_dir"`
	// The tray's GPU occupancy file (fake GPU stack's shared state), read
	// only: source of the GPU sensors.
	TelemetryPath string `json:"telemetry_path"`
	Incus         Incus  `json:"incus"`

	// nvswitch role: the switch chips, their ports, and the trays whose GPUs
	// are cabled to them (in order; GPU numbering continues across trays).
	Switches    int        `json:"switches"`
	SwitchPorts int        `json:"switch_ports"`
	Trays       []TrayLink `json:"trays"`
}

// TrayLink is a GPU tray as seen from the switch tray: its name and the
// sideband directory the switch BMC writes link state into.
type TrayLink struct {
	Name        string `json:"name"`
	SidebandDir string `json:"sideband_dir"`
}

// Incus is the API endpoint used for tray power control. The client
// certificate is trusted only for the project holding the GPU trays.
type Incus struct {
	URL        string `json:"url"`
	Project    string `json:"project"`
	Cert       string `json:"cert"`
	Key        string `json:"key"`
	ServerCert string `json:"server_cert"`
}

func loadConfig(path string) (*Config, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return nil, err
	}
	cfg := &Config{Role: "tray", Listen: ":443", ProductName: "GB200 NVL", VBIOSVersion: "97.00.82.00.0F", GPUCount: 4,
		PowerLimitW: 1200, IdlePowerW: 140, MaxPowerW: 1000, NVLinkLinkGbs: 50,
		NVSwitchFirmware: "fakebmc-nvswitch-1", CPLDFirmware: "fakebmc-cpld-1", NVLinks: 18, Username: "root", StateDir: "/var/lib/fakebmc",
		Switches: 2, SwitchPorts: 72}
	if err := json.Unmarshal(data, cfg); err != nil {
		return nil, fmt.Errorf("%s: %w", path, err)
	}
	if cfg.Password == "" {
		return nil, fmt.Errorf("%s: password is required", path)
	}
	switch cfg.Role {
	case "tray":
		if cfg.Tray == "" {
			return nil, fmt.Errorf("%s: tray is required", path)
		}
	case "nvswitch":
		if len(cfg.Trays) == 0 || cfg.Switches < 1 || cfg.NVLinks%cfg.Switches != 0 ||
			len(cfg.Trays)*cfg.GPUCount*cfg.NVLinks > cfg.Switches*cfg.SwitchPorts {
			return nil, fmt.Errorf("%s: trays x gpu_count x nvlinks must fit switches x switch_ports", path)
		}
	default:
		return nil, fmt.Errorf("%s: unknown role %q", path, cfg.Role)
	}
	if cfg.SidebandDir == "" {
		cfg.SidebandDir = cfg.StateDir + "/sideband"
	}
	if cfg.BMCFirmware == "" {
		cfg.BMCFirmware = "fakebmc-" + version
	}
	if cfg.HMCFirmware == "" {
		cfg.HMCFirmware = "fakebmc-hmc-" + version
	}
	idleMW, maxMW, powerLimitW = cfg.IdlePowerW*1000, cfg.MaxPowerW*1000, cfg.PowerLimitW
	return cfg, nil
}
